services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app
    depends_on:
      - db

volumes:
  postgres_data: